<?php
/**
 * Класс Image
 */

namespace App\FileSystem;

use App\Config;
use App\FileSystem\File;

class Image extends File
{
    public $name;
    public $height;
    public $width;
    public $type;
    public $pathToFile;

    public function __construct($pathToFile)
    {
        $this->pathToFile = $pathToFile;
        if(file_exists($pathToFile)) {
            $this->upload();
        }
    }

    public function upload()
    {

    }

    protected function getUploadSettings()
    {
        return Config::getInstance()->getConfig('images');
    }


    public function delete($paths)
    {
        return parent::delete($paths); // TODO: Change the autogenerated stub
    }
}

